# Generated by Django 4.2.1 on 2023-06-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.FloatField(default=0),
        ),
    ]
